



TAG_MAPPING = {
    "entry": "div",
    "BusyuHeadKaisetsuG": "div",
    "BusyuHeadG": "div",
    "BusyuHeadSubG": "table",
    "BusyuHeadC": "tr",
    "BusyuKakusuG": "td",
    "BusyuNumberG": "td",
    "BusyuBusyuG": "td",
    "BusyuBusyuLabelG": "td",
    "BusyuYomiG": "div",
    "BusyuYomiContent": "div",
    "BushuKaisetsuG": "div",
    "BusyuKaisetsuSubG": "div",
    "BushubetsuIndexG": "div",
    "BushubetsuIndexContentG": "table",
    "BusyubetsuIndexSubG": "tr",
    "BusyuNaiKakusuLabel": "td",
    "BusyuMidashijiG": "td",
    "ShinsetsuMidashiG": "div",
    "ShinsetsuMidashiContent": "div",
    "MidashijiInfoG": "div",
    "MidashijiInfoSubG": "div",
    "ItaijiKyujiInfoSubG": "div",
    "KyujiListG": "div",
    "ItaijiListG": "div",
    "ItaijiKyujiInfoG": "div",
    "KanjiInfoHeadG": "table",
    "KanjiInfoHeadSubG": "tr",
    "BranchNumberG": "td",
    "KenjiNumberG": "td",
    "KanjiBusyuG": "td",
    "KanjiSoukakusuG": "td",
    "MenkutenCodeG": "td",
    "UnicodeG": "td",
    "ItaijiLabelG": "td",
    "KanjiG": "td",
    "OnListG": "div",
    "KokujiG": "div",
    "JoyoOnkunG": "div",
    "FuhyoG": "div",
    "OnListSubG": "div",
    "HonmonG": "div",
    "NaritachiG": "div",
    "ImiG": "div",
    "Imi": "div",
    "Imi.inline": "span",
    "JukugoItem Imi": "span",
    "SankouG": "div",
    "Sankou": "div",
    "Sankou.inline": "span",
    "JinmeiG": "div",
    "ImageListG": "div",
    "ImageG": "div",
    "ImageContentG": "div",
    "ImageCaption": "div",
    "ImageFile": "div",
    "JukugoG": "div",
    "JukugoList": "div",
    "JukugoItem": "div",
    "JukugoItem HonmonG": "span",
    "JukugoItem ImiG": "span",
    "JukugoItem Imi": "span",
    "JukugoItemContent": "div",
    "SankouJukugoG": "div",
    "Nandoku": "div",
    "SankouJukugo": "div",
    "GyakuJukugo": "div",
    "DaggerRef": "div",
    "TAG": "div",
    "TAG": "div",
    "TAG": "div",
    "TAG": "div",
    "TAG": "div",

}